### PR TITLE
Added support for new composer installed.json format

### PR DESCRIPTION
**Pull request by sixcare**
Fixes issue https://github.com/auraphp/Aura.Project_Kernel/issues/13

### CODE REVIEW

**Comment by pmjones** [comment]
Hey @sixcare it looks like the Travis tests fail -- any thoughts on how to remedy?

**Comment by sixcare** [comment]
> Hey @sixcare it looks like the Travis tests fail -- any thoughts on how to remedy?

I'm not quite familiar with the Travis test.

From what I can see the PHP7 test failed because of this:
```
This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.
You are using PHP 7.0.33 (/home/travis/.phpenv/versions/7.0.33/bin/php).
The command "phpunit --coverage-clover=coverage.clover" exited with 1.
```

the PHP5.6 test completed 
```
OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 9, Skipped: 1.
```

If you're on IRC I'd be happy to chat with you about this Issue and pull-request @pmjones

**Comment by harikt** [comment]
Hey @sixcare , @kenjis has merged your PR on https://github.com/auraphp/Aura.Project_Kernel/pull/15 . So I guess this should have been fixed.

In case if you find any issues we can reopen it. Thanks once again for the PR.

**Comment by harikt** [comment]
Fixing this in 2.x branch. Thank you @sixcare .

**Pull request merged**
