### PR TITLE
Do not execute the common config twice.

### PR DESCRIPTION
**Pull request by ralouphie**
Common config is executing twice. This prevents that.

### CODE REVIEW

**Comment by harikt** [comment]
https://github.com/ralouphie/Aura.Project_Kernel/blob/common2x/src/Factory.php#L43

To my understanding it will only execute once if mode is not set explicitly as common in environment https://github.com/auraphp/Aura.Web_Project/blob/master/config/_env.php

@pmjones will look into this and merge.

**Comment by pmjones** [comment]
@ralouphie when you say "Common config is executing twice," which do you mean:
1. Only when the config mode is explicitly set to "common", or
2. No matter what the config mode is?

The answer will help me evaluate the PR. And thanks!

**Comment by ralouphie** [comment]
@pmjones Sorry for the lack of clarification. I meant (1) when the mode is explicitly set to "common".

**Comment by harikt** [comment]
@ralouphie common is not a mode in my opinion. I leave this for Paul to decide :) .

**Comment by ralouphie** [comment]
I think it would be useful to be able to use the common config. But if not I think it should at least throw an exception so it's clear.

**Comment by harikt** [comment]
The common is always loaded. 
Anyway I leave this to Paul.

**Comment by pmjones** [comment]
I can see a case where the developer might want to load _only_ the common config, so I'm OK with this. Thanks @ralouphie , and thanks @harikt for reviewing.

**Comment by harikt** [comment]
You are welcome Paul :) .

Happy to see you moving things :-) .

**Pull request merged**
