### PR TITLE
Update for PHP 7.2, 7.3 and 7.4

### PR DESCRIPTION
**Pull request by kenjis**
Fixes issue #13
Includes #14

- Add support for composer 2 installed.json format
- Update Aura.Di version
- Add PHPUnit as dev dependency

### CODE REVIEW

**Comment by kenjis** [comment]
@pmjones @harikt Could you review this PR?

**Comment by harikt** [comment]
Hey @kenjis , 

Thank you for the PR. As far as I know we were restricting the php version changes. So not sure this can be merged in that sense. 

But my take is this can be merged for php has moved a lot to 8.x . And I don't know if there will be another 3.x for Aura framework.

I will leave the decision to pmjones.

**Comment by kenjis** [comment]
@pmjones @harikt @koriym
I hope this PR will be merged.

But this is for PHP 7.x. So it should be merged into 4.x.
See https://github.com/auraphp/Aura.Cli_Kernel/pull/12#issuecomment-873248524
Can you create `4.x` branch?

**Comment by harikt** [comment]
4.x is created. Let me know if you need anything else.

**Comment by kenjis** [comment]
@pmjones @harikt @koriym
I've finished this PR. But Travis is gone and Scrutinizer raised error.

In my local environment, phpunit testing passed:
```sh-session
kenji:~/work/aura/Aura.Project_Kernel (3.x)$ /usr/local/opt/php\@7.2/bin/php vendor/bin/phpunit 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

........S                                                           9 / 9 (100%)

Time: 116 ms, Memory: 4.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 9, Skipped: 1.
kenji:~/work/aura/Aura.Project_Kernel (3.x)$ /usr/local/opt/php\@7.3/bin/php vendor/bin/phpunit 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

........S                                                           9 / 9 (100%)

Time: 59 ms, Memory: 4.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 9, Skipped: 1.
kenji:~/work/aura/Aura.Project_Kernel (3.x)$ /usr/local/opt/php\@7.4/bin/php vendor/bin/phpunit 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

........S                                                           9 / 9 (100%)

Time: 53 ms, Memory: 4.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 9, Skipped: 1.
```

What shall we do?

**Comment by kenjis** [comment]
```sh-session
kenji:~/work/aura/Aura.Project_Kernel (3.x)$ /usr/local/opt/php\@8.0/bin/php vendor/bin/phpunit 
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

........S                                                           9 / 9 (100%)

Time: 65 ms, Memory: 4.00 MB

OK, but incomplete, skipped, or risky tests!
Tests: 9, Assertions: 9, Skipped: 1.
```

**Comment by harikt** [comment]
I can look into the test issues in this weekend. You can merge the branches in 4.x for now. pmjones has already approved the travis.com , but due to some reason the builds are not ready.

**Comment by kenjis** [comment]
phpunit 7 can't be installed on php8.
```
  Problem 1
    - phpunit/phpunit[7.0.0, ..., 7.5.20] require php ^7.1 -> your php version (8.0.8) does not satisfy that requirement.
    - Root composer.json requires phpunit/phpunit ~7 -> satisfiable by phpunit/phpunit[7.0.0, ..., 7.5.20].
```

I will update to phpunit 8.x. Because phpunit 8 requires php 7.2 or later and supports php8.
phpunit 9 requires php 7.3 or later.

**Comment by harikt** [comment]
I have updated the github workflow. You can try again.

**Comment by harikt** [comment]
@kenjis if this works you can make the necessary changes to all other repos also.

**Comment by harikt** [comment]
FYI : I have created https://github.com/auraphp/Aura.Project_Kernel/pull/18 for testing. You can see the phpunit it complains is due to wrong code. So all seems well.

**Comment by harikt** [comment]
image


You can see the build. update the .github/actions/php.yml with the php version you need. 

https://stackoverflow.com/questions/57965588/how-to-test-with-different-versions-of-php-in-a-github-action

**Comment by kenjis** [comment]
@harikt Thanks!

https://github.com/auraphp/Aura.Project_Kernel/pull/15#issuecomment-878849147
I will send another PR for it.

**Comment by harikt** [comment]
Please refer composer.json and .github/workflows/php.yml for other repos you want the ci. I am moving on.

**Pull request merged**
